import type { I } from '@/components/icons.tsx'
// PRD s6 navigation. Each entry names the permission or role that shows it; the database enforces the rest.
export const NAV: { href: string; label: string; icon: keyof typeof I; perm?: string; roles?: string[]; group: 'main' | 'secondary' | 'admin' }[] = [
  { href: '/', label: 'Dashboard', icon: 'dashboard', group: 'main' },
  { href: '/leads', label: 'Leads', icon: 'leads', group: 'main' },
  { href: '/opportunities', label: 'Opportunities', icon: 'deals', group: 'main' },
  { href: '/todos', label: 'To-dos', icon: 'todos', group: 'main' },
  { href: '/engagements', label: 'Engagements', icon: 'engagements', group: 'main', roles: ['SUPERADMIN', 'HQ_ADMIN', 'DISTRICT_MANAGER', 'CENTRE_ADMIN'] },
  { href: '/conversations', label: 'Conversations', icon: 'conversations', group: 'main', perm: 'conversations.send' },
  { href: '/catalogue', label: 'Catalogue', icon: 'catalogue', group: 'secondary' },
  { href: '/lists', label: 'Lists', icon: 'lists', group: 'secondary' },
  { href: '/reports', label: 'Reports', icon: 'reports', group: 'secondary' },
  { href: '/exports', label: 'Exports', icon: 'exports', group: 'secondary', perm: 'leads.export' },
  { href: '/integrations', label: 'Integrations', icon: 'integrations', group: 'secondary', perm: 'integrations.manage' },
  { href: '/admin/districts', label: 'Districts', icon: 'admin', group: 'admin', perm: 'centres.manage' },
  { href: '/admin/centres', label: 'Centres', icon: 'admin', group: 'admin', roles: ['SUPERADMIN', 'HQ_ADMIN', 'DISTRICT_MANAGER'] },
  { href: '/admin/users', label: 'Users', icon: 'users', group: 'admin', perm: 'users.manage' },
  { href: '/admin/permissions', label: 'Roles & permissions', icon: 'admin', group: 'admin', roles: ['SUPERADMIN'] },
  { href: '/admin/config', label: 'Lead configuration', icon: 'sliders', group: 'admin', perm: 'config.manage' },
  { href: '/admin/routing', label: 'Routing', icon: 'sliders', group: 'admin', perm: 'routing.manage' },
  { href: '/admin/automation', label: 'Automation', icon: 'spark', group: 'admin', perm: 'automation.manage' },
  { href: '/admin/templates', label: 'Templates', icon: 'conversations', group: 'admin', perm: 'broadcasts.manage' },
  { href: '/admin/broadcasts', label: 'Broadcasts', icon: 'conversations', group: 'admin', perm: 'broadcasts.manage' },
  { href: '/admin/properties', label: 'Custom properties', icon: 'sliders', group: 'admin', perm: 'config.manage' },
  { href: '/admin/payouts', label: 'Payouts', icon: 'deals', group: 'admin', perm: 'reports.payouts' },
  { href: '/admin/conflicts', label: 'Conflicts', icon: 'alert', group: 'admin', perm: 'conflicts.resolve' },
  { href: '/admin/inbound', label: 'Inbound events', icon: 'inbox', group: 'admin', perm: 'inbound.replay' },
  { href: '/admin/health', label: 'System health', icon: 'engagements', group: 'admin', roles: ['SUPERADMIN', 'HQ_ADMIN'] },
  { href: '/admin/dnc', label: 'Do Not Contact', icon: 'phone', group: 'admin', perm: 'dnc.manage' },
  { href: '/admin/migration', label: 'Salesmax import', icon: 'exports', group: 'admin', roles: ['SUPERADMIN', 'HQ_ADMIN'] },
  { href: '/admin/audit', label: 'Audit log', icon: 'clock', group: 'admin', perm: 'audit.view' },
  { href: '/leads/import', label: 'Data import', icon: 'exports', group: 'admin', perm: 'leads.import' },
]
