// PRD s6 navigation. Each entry names the permission or role that shows it; the database enforces the rest.
export const NAV: { href: string; label: string; perm?: string; roles?: string[]; group: 'main' | 'secondary' | 'admin' }[] = [
  { href: '/', label: 'Dashboard', group: 'main' },
  { href: '/leads', label: 'Leads', group: 'main' },
  { href: '/opportunities', label: 'Opportunities', group: 'main' },
  { href: '/todos', label: 'To-dos', group: 'main' },
  { href: '/engagements', label: 'Engagements', group: 'main', roles: ['SUPERADMIN', 'HQ_ADMIN', 'DISTRICT_MANAGER', 'CENTRE_ADMIN'] },
  { href: '/conversations', label: 'Conversations', group: 'main', perm: 'conversations.send' },
  { href: '/catalogue', label: 'Catalogue', group: 'secondary' },
  { href: '/lists', label: 'Lists', group: 'secondary' },
  { href: '/reports', label: 'Reports', group: 'secondary' },
  { href: '/exports', label: 'Exports', group: 'secondary', perm: 'leads.export' },
  { href: '/integrations', label: 'Integrations', group: 'secondary', perm: 'integrations.manage' },
  { href: '/admin/districts', label: 'Districts', group: 'admin', perm: 'centres.manage' },
  { href: '/admin/centres', label: 'Centres', group: 'admin', roles: ['SUPERADMIN', 'HQ_ADMIN', 'DISTRICT_MANAGER'] },
  { href: '/admin/users', label: 'Users', group: 'admin', perm: 'users.manage' },
  { href: '/admin/permissions', label: 'Roles & permissions', group: 'admin', roles: ['SUPERADMIN'] },
  { href: '/admin/config', label: 'Lead configuration', group: 'admin', perm: 'config.manage' },
  { href: '/admin/routing', label: 'Routing', group: 'admin', perm: 'routing.manage' },
  { href: '/admin/automation', label: 'Automation', group: 'admin', perm: 'automation.manage' },
  { href: '/admin/templates', label: 'Templates', group: 'admin', perm: 'broadcasts.manage' },
  { href: '/admin/broadcasts', label: 'Broadcasts', group: 'admin', perm: 'broadcasts.manage' },
  { href: '/admin/properties', label: 'Custom properties', group: 'admin', perm: 'config.manage' },
  { href: '/admin/payouts', label: 'Payouts', group: 'admin', perm: 'reports.payouts' },
  { href: '/admin/conflicts', label: 'Conflicts', group: 'admin', perm: 'conflicts.resolve' },
  { href: '/admin/inbound', label: 'Inbound events', group: 'admin', perm: 'inbound.replay' },
  { href: '/admin/health', label: 'System health', group: 'admin', roles: ['SUPERADMIN', 'HQ_ADMIN'] },
  { href: '/admin/dnc', label: 'Do Not Contact', group: 'admin', perm: 'dnc.manage' },
  { href: '/admin/migration', label: 'Salesmax import', group: 'admin', roles: ['SUPERADMIN', 'HQ_ADMIN'] },
  { href: '/admin/audit', label: 'Audit log', group: 'admin', perm: 'audit.view' },
  { href: '/leads/import', label: 'Data import', group: 'admin', perm: 'leads.import' },
]
