import { ActionForm } from '@/components/form.tsx'
import { Page, Table } from '@/components/ui.tsx'
import { tenant } from '@/lib/session.ts'
import { dealStageAction, dispositionAction, leadConfigAction, lifecycleLabelAction, toggleActiveAction } from '../../more-actions.ts'
const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
export default async function Config() {
  const d = await tenant(async (db, c) => ({ ro: c.read_only,
    org: (await db.query('select cadence_days, calling_start::text, calling_end::text, working_days, sla_first_touch_minutes, sla_untouched_hours, cross_centre_policy, referral_window_days, renewal_lead_days from orgs')).rows[0],
    disps: (await db.query<{ id: string; name: string; sentiment: string; effect: string; followup: string; followup_days: number | null; note_required: boolean; creates_deal: boolean; add_tag: string | null; sort: number; is_active: boolean }>('select * from dispositions order by sort, name')).rows,
    labels: Object.fromEntries((await db.query<{ state: string; label: string }>('select state, label from lifecycle_labels')).rows.map((r) => [r.state, r.label])),
    stages: (await db.query<{ id: string; name: string; sort: number; is_won: boolean; is_lost: boolean; is_active: boolean }>('select * from deal_stages order by sort')).rows }))
  const o = d.org
  return <Page title="Lead configuration" sub="Everything here is data. Changes are audited.">
    <ActionForm action={leadConfigAction} submit="Save settings" className="panel grid gap-3 p-4 md:grid-cols-3">
      <div><label className="label" htmlFor="cadence_days">Prospecting cadence (days after first call)</label><input id="cadence_days" name="cadence_days" defaultValue={o.cadence_days.join(', ')} className="input" /><p className="mt-1 text-xs text-muted">Max attempts = number of entries (TE-2)</p></div>
      <div><label className="label">Calling hours (lead&apos;s timezone)</label><div className="flex gap-2"><input type="time" name="calling_start" defaultValue={o.calling_start.slice(0, 5)} className="input" aria-label="Start" /><input type="time" name="calling_end" defaultValue={o.calling_end.slice(0, 5)} className="input" aria-label="End" /></div></div>
      <div><label className="label">Working days</label><div className="flex flex-wrap gap-2 text-sm">{DAYS.map((n, i) => <label key={n}><input type="checkbox" name="working_days" value={i + 1} defaultChecked={o.working_days.includes(i + 1)} /> {n}</label>)}</div></div>
      <div><label className="label" htmlFor="sla_first_touch_minutes">First-touch SLA (working minutes)</label><input id="sla_first_touch_minutes" name="sla_first_touch_minutes" type="number" defaultValue={o.sla_first_touch_minutes} className="input" /></div>
      <div><label className="label" htmlFor="sla_untouched_hours">Untouched → HQ dashboard (hours)</label><input id="sla_untouched_hours" name="sla_untouched_hours" type="number" defaultValue={o.sla_untouched_hours} className="input" /></div>
      <div><label className="label" htmlFor="cross_centre_policy">Cross-centre duplicate policy</label><select id="cross_centre_policy" name="cross_centre_policy" defaultValue={o.cross_centre_policy} className="input"><option value="first_touch_wins">First touch wins</option><option value="hq_decides">HQ decides each case</option></select></div>
      <div><label className="label" htmlFor="referral_window_days">Referral attribution window (days)</label><input id="referral_window_days" name="referral_window_days" type="number" defaultValue={o.referral_window_days} className="input" /></div>
      <div><label className="label" htmlFor="renewal_lead_days">Renewal deal created (days before access ends)</label><input id="renewal_lead_days" name="renewal_lead_days" type="number" defaultValue={o.renewal_lead_days} className="input" /></div>
    </ActionForm>
    <section className="panel p-4"><h2 className="font-medium">Lifecycle labels</h2><p className="text-sm text-muted">Internal states are fixed; labels are what users see.</p><div className="mt-2 flex flex-wrap gap-2">{['ENQUIRY', 'PROSPECT', 'INTERESTED', 'DEAD', 'ENROLLED'].map((s) => <form key={s} action={lifecycleLabelAction} className="flex gap-1"><input type="hidden" name="state" value={s} /><input name="label" defaultValue={d.labels[s] ?? s[0] + s.slice(1).toLowerCase()} className="input h-8 w-32" aria-label={s} /><button className="btn btn-quiet h-8">Save</button></form>)}</div></section>
    <section className="space-y-3"><h2 className="font-medium">Dispositions</h2>
      <Table head={['#Sort', 'Name', 'Sentiment', 'Effect', 'Follow-up', 'Flags', 'Status', '']}>
        {d.disps.map((x) => <tr key={x.id}><td className="td text-right tabular-nums">{x.sort}</td><td className="td font-medium">{x.name}</td><td className="td">{x.sentiment}</td><td className="td">{x.effect.replace('to_', '→ ').replace('none', 'stay')}</td><td className="td">{x.followup === 'days' ? `${x.followup_days} days` : x.followup}</td><td className="td text-xs text-muted">{[x.note_required && 'note required', x.creates_deal && 'creates deal', x.add_tag && `tag: ${x.add_tag}`].filter(Boolean).join(', ')}</td><td className="td"><span className={`chip ${x.is_active ? 'text-ok' : 'text-muted'}`}>{x.is_active ? 'Active' : 'Off'}</span></td>
          <td className="td text-right">{!d.ro && <form action={toggleActiveAction}><input type="hidden" name="table" value="dispositions" /><input type="hidden" name="id" value={x.id} /><input type="hidden" name="active" value={String(!x.is_active)} /><button className="btn btn-quiet h-8">{x.is_active ? 'Disable' : 'Enable'}</button></form>}</td></tr>)}</Table>
      {!d.ro && <ActionForm action={dispositionAction} submit="Add disposition" className="panel grid gap-2 p-4 md:grid-cols-4 lg:grid-cols-8 lg:items-end">
        <div className="lg:col-span-2"><label className="label" htmlFor="dname">Name</label><input id="dname" name="name" className="input" required /></div>
        <div><label className="label" htmlFor="sentiment">Sentiment</label><select id="sentiment" name="sentiment" className="input">{['positive', 'neutral', 'negative', 'junk'].map((s) => <option key={s}>{s}</option>)}</select></div>
        <div><label className="label" htmlFor="effect">Effect</label><select id="effect" name="effect" className="input"><option value="none">Stay</option><option value="to_interested">→ Interested</option><option value="to_dead">→ Dead</option><option value="to_enrolled">→ Enrolled</option></select></div>
        <div><label className="label" htmlFor="followup">Follow-up</label><select id="followup" name="followup" className="input"><option value="cadence">Per cadence</option><option value="days">Fixed days</option><option value="user">User picks time</option><option value="none">None</option></select></div>
        <div><label className="label" htmlFor="followup_days">Days</label><input id="followup_days" name="followup_days" type="number" className="input" /></div>
        <div><label className="label" htmlFor="add_tag">Adds tag</label><input id="add_tag" name="add_tag" className="input" /></div>
        <div className="flex flex-col gap-1 text-sm"><label><input type="checkbox" name="note_required" /> Note required</label><label><input type="checkbox" name="creates_deal" /> Creates deal</label></div>
      </ActionForm>}</section>
    <section className="space-y-3"><h2 className="font-medium">Deal stages</h2>
      <Table head={['#Sort', 'Stage', 'Flags', 'Status', '']}>{d.stages.map((s) => <tr key={s.id}><td className="td text-right tabular-nums">{s.sort}</td><td className="td font-medium">{s.name}</td><td className="td">{s.is_won && <span className="chip text-ok">Won</span>}{s.is_lost && <span className="chip text-danger">Lost</span>}</td><td className="td"><span className={`chip ${s.is_active ? 'text-ok' : 'text-muted'}`}>{s.is_active ? 'Active' : 'Off'}</span></td>
        <td className="td text-right">{!d.ro && <form action={toggleActiveAction}><input type="hidden" name="table" value="deal_stages" /><input type="hidden" name="id" value={s.id} /><input type="hidden" name="active" value={String(!s.is_active)} /><button className="btn btn-quiet h-8">{s.is_active ? 'Disable' : 'Enable'}</button></form>}</td></tr>)}</Table>
      {!d.ro && <ActionForm action={dealStageAction} submit="Add stage" className="panel flex flex-wrap items-end gap-2 p-4"><div><label className="label" htmlFor="sname">Name</label><input id="sname" name="name" className="input" required /></div><div><label className="label" htmlFor="ssort">Sort</label><input id="ssort" name="sort" type="number" defaultValue={10} className="input w-24" /></div><label className="text-sm"><input type="checkbox" name="is_won" /> Won</label><label className="text-sm"><input type="checkbox" name="is_lost" /> Lost</label></ActionForm>}</section>
  </Page>
}
