import Link from 'next/link'
import { money, Page, Table } from '@/components/ui.tsx'
import { funnelQuery, pct, PIVOTS, type Pivot } from '@/lib/reports.ts'
import { tenant } from '@/lib/session.ts'
type Row = { key: string | null; filter_value: string | null; total: number; enquiry: number; rechurned: number; prospect: number; interested: number; dead: number; enrolled: number; revenue: number; touched: number; opportunities: number; junk: number }
// RP-1..5, RP-11: one funnel grid, pivoted; every cell links to the lead list with the same filters (RP-7).
export default async function Reports({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const sp = await searchParams
  const pivot = (sp.pivot && sp.pivot in PIVOTS ? sp.pivot : 'source') as Pivot
  const report = sp.report === 'activity' ? 'activity' : sp.report === 'campaign' ? 'campaign' : sp.report === 'leaderboard' ? 'leaderboard' : 'funnel'
  const filters = { from: sp.from, to: sp.to, closed_from: sp.closed_from, closed_to: sp.closed_to, centre: sp.centre, district: sp.district }
  const d = await tenant(async (db, c) => {
    const q = funnelQuery(pivot, filters, c)
    const rows = report === 'funnel' ? (await db.query<Row>(q.sql, q.params)).rows : []
    const centres = c.centre_id ? [] : (await db.query<{ id: string; code: string }>('select id, code from centres where is_active order by code')).rows
    const activity = report === 'activity' ? (await db.query<{ who: string; calls: number; unique_calls: number; connected: number; disposed: number; positive: number; negative: number; tasks: number; deals: number }>(
      `select coalesce(u.display_name, 'System') as who, count(*) filter (where a.type = 'call_outcome')::int calls, count(distinct a.lead_id) filter (where a.type = 'call_outcome')::int unique_calls,
              count(*) filter (where a.type = 'call_outcome' and a.disposition <> 'Not reachable')::int connected, count(*) filter (where a.type = 'call_outcome')::int disposed,
              count(*) filter (where a.sentiment = 'positive')::int positive, count(*) filter (where a.sentiment in ('negative','junk'))::int negative,
              count(*) filter (where a.type = 'task_completed')::int tasks, count(*) filter (where a.type = 'deal_created')::int deals
       from activity_scope a left join users u on u.id = a.actor_user_id where a.created_at >= coalesce($1::date, now() - interval '30 days') and a.created_at < coalesce($2::date + 1, now() + interval '1 day') group by 1 order by calls desc limit 200`, [sp.from ?? null, sp.to ?? null])).rows : []
    const leaderboard = report === 'leaderboard' ? (await db.query<{ code: string; id: string; speed_min: number | null; untouched: number; overdue: number; work_done: number; total: number; enrolled: number; revenue: number }>(
      `select c.code, c.id, round(avg(extract(epoch from (v.first_touch_at - v.enquiry_at)) / 60))::int as speed_min, count(*) filter (where v.attempts = 0 and v.lifecycle = 'ENQUIRY')::int untouched,
              count(*) filter (where v.next_followup_at < now() and v.lifecycle in ('ENQUIRY','PROSPECT','INTERESTED'))::int overdue, count(*) filter (where v.first_touch_at is not null)::int work_done, count(*)::int total,
              count(*) filter (where v.lifecycle = 'ENROLLED')::int enrolled, coalesce(sum(v.total_paid), 0)::float revenue
       from lead_list v join centres c on c.id = v.current_centre_id where v.anonymised_at is null and v.created_at >= coalesce($1::date, now() - interval '90 days') group by 1, 2 order by enrolled desc, work_done desc limit 500`, [sp.from ?? null])).rows : []
    const campaign = report === 'campaign' ? (await db.query<{ centre: string | null; campaign: string; spend: number; currency: string; leads: number; interested: number; enrolled: number; revenue: number }>(
      `with sp as (select centre_id, campaign_id, sum(spend)::float spend, min(currency) currency, max(campaign_name) campaign_name from campaign_spend where day >= coalesce($1::date, now() - interval '30 days') group by 1, 2),
            ld as (select current_centre_id centre_id, campaign_id, count(*)::int leads, count(*) filter (where lifecycle in ('INTERESTED','ENROLLED') or became_opportunity_at is not null)::int interested, count(*) filter (where lifecycle = 'ENROLLED')::int enrolled, coalesce(sum(total_paid), 0)::float revenue
                   from lead_list where campaign_id is not null and created_at >= coalesce($1::date, now() - interval '30 days') group by 1, 2)
       select c.code as centre, coalesce(sp.campaign_name, ld.campaign_id, sp.campaign_id) as campaign, coalesce(sp.spend, 0) spend, coalesce(sp.currency, 'INR') currency, coalesce(ld.leads, 0) leads, coalesce(ld.interested, 0) interested, coalesce(ld.enrolled, 0) enrolled, coalesce(ld.revenue, 0) revenue
       from sp full join ld on ld.centre_id is not distinct from sp.centre_id and ld.campaign_id = sp.campaign_id left join centres c on c.id = coalesce(sp.centre_id, ld.centre_id)
       where c.id is null or app.can_see(c.org_id, c.district_id, c.id) order by spend desc limit 500`, [sp.from ?? null])).rows : []
    return { rows, centres, activity, leaderboard, campaign, claims: c }
  })
  const qs = (over: Record<string, string | undefined>) => { const u = new URLSearchParams(); for (const [k, v] of Object.entries({ ...sp, ...over })) if (v) u.set(k, v); return `?${u}` }
  const drill = (r: Row, extra: Record<string, string> = {}) => { const u = new URLSearchParams({ view: 'all', ...Object.fromEntries(Object.entries(filters).filter(([, v]) => v)) as Record<string, string>, ...extra }); if (r.filter_value) u.set(PIVOTS[pivot].filter, r.filter_value); return `/leads?${u}` }
  const tot = d.rows.reduce((a, r) => ({ total: a.total + r.total, enquiry: a.enquiry + r.enquiry, rechurned: a.rechurned + r.rechurned, prospect: a.prospect + r.prospect, interested: a.interested + r.interested, dead: a.dead + r.dead, enrolled: a.enrolled + r.enrolled, revenue: a.revenue + r.revenue, touched: a.touched + r.touched, opportunities: a.opportunities + r.opportunities, junk: a.junk + r.junk, key: 'Total', filter_value: null }), { total: 0, enquiry: 0, rechurned: 0, prospect: 0, interested: 0, dead: 0, enrolled: 0, revenue: 0, touched: 0, opportunities: 0, junk: 0, key: 'Total', filter_value: null } as Row)
  const cell = (r: Row, k: keyof Row, extra?: Record<string, string>) => <td className="td text-right tabular-nums"><Link href={drill(r, extra)} className="hover:underline">{typeof r[k] === 'number' && k === 'revenue' ? money(r[k]) : String(r[k])}</Link></td>
  const Row = ({ r, bold }: { r: Row; bold?: boolean }) => <tr className={bold ? 'font-semibold' : ''}><td className="td">{r.key ?? '—'}</td>{cell(r, 'total')}{cell(r, 'enquiry', { lifecycle: 'ENQUIRY' })}{cell(r, 'rechurned', { rechurned: '1' })}{cell(r, 'prospect', { lifecycle: 'PROSPECT' })}{cell(r, 'interested', { lifecycle: 'INTERESTED' })}{cell(r, 'dead', { lifecycle: 'DEAD' })}{cell(r, 'enrolled', { lifecycle: 'ENROLLED' })}{cell(r, 'revenue', { lifecycle: 'ENROLLED' })}
    <td className="td text-right tabular-nums">{pct(r.touched, r.total)}</td><td className="td text-right tabular-nums">{pct(r.junk, r.total)}</td><td className="td text-right tabular-nums">{pct(r.opportunities, r.total)}</td><td className="td text-right tabular-nums">{pct(r.enrolled, r.opportunities)}</td></tr>
  return <Page title="Reports" sub="Every number opens the leads behind it." action={<div className="flex gap-1">{[['funnel', 'Funnel'], ['leaderboard', 'Centre leaderboard'], ['activity', 'Activity'], ['campaign', 'Campaigns']].map(([k, l]) => <Link key={k} href={qs({ report: k })} aria-current={report === k ? 'page' : undefined} className="seg">{l}</Link>)}</div>}>
    <form className="panel flex flex-wrap items-end gap-3 p-3"><input type="hidden" name="report" value={report} />
      {report === 'funnel' && <label className="block"><span className="label">Pivot</span><select name="pivot" defaultValue={pivot} className="input w-44">{Object.entries(PIVOTS).map(([k, v]) => <option key={k} value={k}>By {v.label}</option>)}</select></label>}
      {d.centres.length > 0 && <label className="block"><span className="label">Centre</span><select name="centre" defaultValue={sp.centre ?? ''} className="input w-36"><option value="">All centres</option>{d.centres.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></label>}
      <label className="block"><span className="label">Created from</span><input type="date" name="from" defaultValue={sp.from ?? ''} className="input w-40" /></label><label className="block"><span className="label">to</span><input type="date" name="to" defaultValue={sp.to ?? ''} className="input w-40" /></label>
      {report === 'funnel' && <><label className="block"><span className="label">Closed from</span><input type="date" name="closed_from" defaultValue={sp.closed_from ?? ''} className="input w-40" /></label><label className="block"><span className="label">to</span><input type="date" name="closed_to" defaultValue={sp.closed_to ?? ''} className="input w-40" /></label></>}
      <button className="btn btn-quiet">Apply</button></form>
    {report === 'funnel' && <Table head={[PIVOTS[pivot].label, '#Total', '#Enquiry', '#Rechurned', '#Prospect', '#Interested', '#Dead', '#Enrolled', '#Revenue', '#Work done', '#Junk', '#Deal conv.', '#Win']} empty={d.rows.length ? undefined : 'No leads match.'}>
      {d.rows.map((r, i) => <Row key={i} r={r} />)}{d.rows.length > 0 && <Row r={tot} bold />}</Table>}
    {report === 'leaderboard' && <Table head={['Centre', '#Speed to first call (min)', '#Untouched', '#Overdue', '#Work done', '#Conversion', '#Enrolled', '#Revenue']} empty={d.leaderboard.length ? undefined : 'No data.'}>
      {d.leaderboard.map((r) => <tr key={r.id}><td className="td font-medium"><Link href={`/leads?view=all&centre=${r.id}`} className="hover:underline">{r.code}</Link></td><td className="td text-right tabular-nums">{r.speed_min ?? '—'}</td><td className="td text-right tabular-nums"><Link href={`/leads?view=all&centre=${r.id}&sla=untouched`} className="hover:underline">{r.untouched}</Link></td><td className="td text-right tabular-nums"><Link href={`/leads?view=overdue&centre=${r.id}`} className="hover:underline">{r.overdue}</Link></td><td className="td text-right tabular-nums">{pct(r.work_done, r.total)}</td><td className="td text-right tabular-nums">{pct(r.enrolled, r.total)}</td><td className="td text-right tabular-nums">{r.enrolled}</td><td className="td text-right tabular-nums">{money(r.revenue)}</td></tr>)}</Table>}
    {report === 'activity' && <Table head={['User', '#Calls', '#Unique calls', '#Connected', '#Disposed', '#Positive', '#Negative', '#Tasks done', '#Deals']} empty={d.activity.length ? undefined : 'No activity in range.'}>
      {d.activity.map((r) => <tr key={r.who}><td className="td font-medium">{r.who}</td>{[r.calls, r.unique_calls, r.connected, r.disposed, r.positive, r.negative, r.tasks, r.deals].map((n, i) => <td key={i} className="td text-right tabular-nums">{n}</td>)}</tr>)}</Table>}
    {report === 'campaign' && <Table head={['Centre', 'Campaign', '#Spend', '#Leads', '#CPL', '#Interested', '#Cost / interested', '#Enrolments', '#Cost / enrolment', '#Revenue', '#ROAS']} empty={d.campaign.length ? undefined : 'No campaign data. Spend arrives once a page has an ad account id (Integrations) and the Marketing API is approved.'}>
      {d.campaign.map((r, i) => <tr key={i}><td className="td">{r.centre ?? 'HQ'}</td><td className="td font-medium">{r.campaign}</td><td className="td text-right tabular-nums">{money(r.spend, r.currency)}</td><td className="td text-right tabular-nums">{r.leads}</td><td className="td text-right tabular-nums">{r.leads ? money(r.spend / r.leads, r.currency) : '—'}</td><td className="td text-right tabular-nums">{r.interested}</td><td className="td text-right tabular-nums">{r.interested ? money(r.spend / r.interested, r.currency) : '—'}</td><td className="td text-right tabular-nums">{r.enrolled}</td><td className="td text-right tabular-nums">{r.enrolled ? money(r.spend / r.enrolled, r.currency) : '—'}</td><td className="td text-right tabular-nums">{money(r.revenue)}</td><td className="td text-right tabular-nums">{r.spend ? (r.revenue / r.spend).toFixed(2) + '×' : '—'}</td></tr>)}</Table>}
  </Page>
}
