import { ActionForm } from '@/components/form.tsx'
import { Page, Table } from '@/components/ui.tsx'
import { tenant } from '@/lib/session.ts'
import { salesmaxStartAction, salesmaxUploadAction } from '../../more-actions.ts'
// MG-1..3 + reconciliation (PRD s15 step 4). Column names in the Salesmax export are UNKNOWN until a sample arrives (NEEDED.md);
// the guesses below are placeholders and every column can be re-mapped here.
const FIELDS: [string, string, RegExp][] = [['salesmax_id', 'Salesmax lead id (dedupe key)', /^id$|lead.?id|salesmax/i], ['phone', 'Phone (required)', /phone|mobile/i], ['name', 'Parent name', /^name|parent|contact/i], ['email', 'Email', /mail/i], ['city', 'City', /city/i], ['state', 'State', /state/i],
  ['student_name', 'Student', /student|child/i], ['grade', 'Grade', /grade|class/i], ['sm_created_at', 'Created date', /creat|added/i], ['sm_owner', 'Owner (username)', /owner|assigned|user/i], ['sm_centre_code', 'Centre code (mapped team/page)', /centre|center|team|branch/i],
  ['sm_lifecycle', 'Lifecycle', /lifecycle|stage|status/i], ['sm_last_disposition', 'Last disposition', /dispos|outcome/i], ['sm_next_followup', 'Next follow-up', /follow|next/i], ['sm_attempts', 'Attempts', /attempt|calls/i], ['sm_closed_reason', 'Closed reason', /reason/i],
  ['sm_source_l1', 'Source', /^source$|channel/i], ['sm_source_l2', 'Source page/account', /page|account/i], ['sm_source_l3', 'Campaign', /campaign/i], ['sm_source_l4', 'Ad/form', /^ad|form/i], ['sm_tags', 'Tags', /tag/i]]
export default async function Migration({ searchParams }: { searchParams: Promise<{ batch?: string }> }) {
  const sp = await searchParams
  const d = await tenant(async (db) => ({
    batches: (await db.query<{ id: string; filename: string; status: string; row_count: number; created_at: Date }>("select id, filename, status, row_count, created_at from import_batches where kind = 'salesmax' order by created_at desc limit 20")).rows,
    batch: sp.batch ? (await db.query<{ id: string; headers: string[]; status: string; row_count: number; mapping: Record<string, string> | null }>("select id, headers, status, row_count, mapping from import_batches where id = $1 and kind = 'salesmax'", [sp.batch])).rows[0] : null,
    recon: sp.batch ? (await db.query<{ dim: string; key: string; salesmax: number; crm: number }>(
      `select 'lifecycle' as dim, coalesce(e.payload->>(b.mapping->>'sm_lifecycle'), '—') as key, count(*)::int as salesmax, count(l.id)::int as crm from inbound_events e join import_batches b on b.id = e.import_batch_id left join leads l on l.id = e.lead_id and e.outcome = 'created' where e.import_batch_id = $1 group by 2
       union all select 'source', coalesce(e.payload->>(b.mapping->>'sm_source_l1'), '—'), count(*)::int, count(l.id)::int from inbound_events e join import_batches b on b.id = e.import_batch_id left join leads l on l.id = e.lead_id and e.outcome = 'created' where e.import_batch_id = $1 group by 2
       union all select 'owner', coalesce(e.payload->>(b.mapping->>'sm_owner'), '—'), count(*)::int, count(l.id)::int from inbound_events e join import_batches b on b.id = e.import_batch_id left join leads l on l.id = e.lead_id and e.outcome = 'created' where e.import_batch_id = $1 group by 2
       union all select 'centre', coalesce(e.payload->>(b.mapping->>'sm_centre_code'), '—'), count(*)::int, count(l.id)::int from inbound_events e join import_batches b on b.id = e.import_batch_id left join leads l on l.id = e.lead_id and e.outcome = 'created' where e.import_batch_id = $1 group by 2
       union all select 'outcome', coalesce(e.outcome, e.processing_status), count(*)::int, 0 from inbound_events e where e.import_batch_id = $1 group by 2 order by 1, 3 desc`, [sp.batch])).rows : [] }))
  return <Page title="Salesmax import" sub="Rows pass through the same ingestion gate as every lead. Re-running the same export creates no duplicates (keyed by the Salesmax lead id). One 'Migrated from Salesmax' event is written per lead.">
    <ActionForm action={salesmaxUploadAction} submit="Upload export" className="panel flex flex-wrap items-end gap-3 p-4"><div><label className="label" htmlFor="file">Salesmax export (Active or Worked Leads, all columns)</label><input id="file" name="file" type="file" accept=".csv,.xlsx" required className="block text-sm" /></div></ActionForm>
    {d.batch && d.batch.status === 'mapping' && <ActionForm action={salesmaxStartAction} submit={`Import ${d.batch.row_count} rows`} className="panel space-y-3 p-4"><input type="hidden" name="batch_id" value={d.batch.id} /><p className="text-[13px] text-muted">Map the export columns. Owner must be the new username; centre must be a centre code (use the mapping sheet for teams and pages).</p>
      <div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{FIELDS.map(([k, label, guess]) => <div key={k}><label className="label" htmlFor={k}>{label}</label><select id={k} name={k} className="input" defaultValue={d.batch!.headers.find((h) => guess.test(h)) ?? ''} required={k === 'phone'}><option value="">—</option>{d.batch!.headers.map((h) => <option key={h}>{h}</option>)}</select></div>)}</div></ActionForm>}
    {d.batch && d.batch.status !== 'mapping' && <Table head={['Dimension', 'Value', '#Salesmax rows', '#CRM leads', '#Difference']}>{d.recon.map((r, i) => <tr key={i}><td className="td">{r.dim}</td><td className="td font-medium">{r.key}</td><td className="td text-right tabular-nums">{r.salesmax}</td><td className="td text-right tabular-nums">{r.dim === 'outcome' ? '' : r.crm}</td><td className={`td text-right tabular-nums ${r.dim !== 'outcome' && r.salesmax !== r.crm ? 'text-warn' : ''}`}>{r.dim === 'outcome' ? '' : r.salesmax - r.crm}</td></tr>)}</Table>}
    <Table head={['File', '#Rows', 'Status', 'Uploaded']} empty={d.batches.length ? undefined : 'No Salesmax imports yet.'}>{d.batches.map((b) => <tr key={b.id}><td className="td"><a href={`?batch=${b.id}`} className="font-medium hover:underline">{b.filename}</a></td><td className="td text-right tabular-nums">{b.row_count}</td><td className="td"><span className="chip">{b.status}</span></td><td className="td text-muted">{b.created_at.toISOString().slice(0, 16).replace('T', ' ')}</td></tr>)}</Table>
    <p className="text-xs text-muted">Differences appear when rows were duplicates, on the DNC list, invalid, or still processing. Parallel run: keep Salesmax read-only for two weeks and re-import Worked Leads at cutover.</p>
  </Page>
}
